---
title: "strobe_diagram_numbers_epr"
author: "Ric Campbell"
date: "07/07/2021"
output: html_document
---

```{r setup, include=FALSE}

library(data.table)
library(readxl)
library(lubridate)
library(tinytex)
library(knitr)
library(kableExtra)

## Add in functions that will be used as can not source like in normal scripts (could if function scripts were packages)

  removeExcludedPatient <- function(final_cohort) {
  
    ## Read in file with removed patients due to death register conflicts
  
      excluded_patients <- readRDS(file = paste("D:/PRIESTDM/data/datasets/cohort", demo_file_id, "excluded_patient_ids.rds", sep = "_"))
  
  
    ## Remove excluded patients
  
      final_cohort_excluded_removed <- final_cohort[!(patient_id %in% excluded_patients)]
  
      return(final_cohort_excluded_removed)
  }

```


```{r create_numbers, echo = FALSE}

## Read in raw data

  epr <- data.table(readRDS("D:/source_data/yas/epr/epr_final_df.rds"))
  
## Keep incidents between dates of interest
  
  epr[, incdate := as.Date(incdate)]
  
  epr <- epr[incdate >= "2020-03-18"]
  epr <- epr[incdate < "2020-06-30"]

  
## rowguid is what became epr_GUID, and then epr_id after being hashed  
    
  number_amb_attendences <- uniqueN(epr[, rowguid])
  
  rm(epr)
  

## Load in epr tables, epr_single has been split on epr_id and contains each one once, therefore has the same rows as the count above
## Load same as at start of B04

  load("data/datasets/epr_tables_freetext_anonymised-2020-09-15 151647.rda")
  
  stopifnot(epr_single_value_fields_tbl[, .N] == number_amb_attendences)

  rm(list = setdiff(ls(), c("removeExcludedPatient", "number_amb_attendences")))
    
  
## Load in data that was saved at end of B04 - linking that was done with CAD also included, and only records with no patient id were removed and saved
## patient ids were attached after discrepancies were sorted
## Want to check numbers flow through processing

  demo_file_id <- "FILE0115974_2021-03-18-163613"
  
  load(paste("data/datasets/cohort", demo_file_id, "epr_freetext_anonymised_data_ssot_dr_outcomes.rda", sep = "_"))
  load(paste("data/datasets/cohort", demo_file_id, "epr_freetext_anonymised_excluded_data.rda", sep = "_"))
  
  stopifnot(epr_single_value_fields_tbl[, .N] + epr_single_value_fields_tbl_excluded[, .N] == number_amb_attendences)
  
  stopifnot(epr_single_value_fields_tbl_excluded[is.na(patient_id), .N] == epr_single_value_fields_tbl_excluded[, .N])
  stopifnot(epr_single_value_fields_tbl[is.na(patient_id), .N] == 0)
  
  number_attendences_not_linked <- epr_single_value_fields_tbl_excluded[, .N]
  
  number_attendences_linked <- epr_single_value_fields_tbl[, .N]
  
  epr_single_excluded_patients_removed <- removeExcludedPatient(epr_single_value_fields_tbl)
  
  number_excluded_patients <- number_attendences_linked - epr_single_excluded_patients_removed[, .N]
  
  rm(list = setdiff(ls(), c("removeExcludedPatient", "number_amb_attendences", "number_attendences_not_linked",
                            "number_attendences_linked", "number_excluded_patients")))
  

## Read in cohort that was sent to stats for final numbers
  
  epr_cohort <- fread("data/data_for_stats/cohort_2021-05-06_ambulance_attended.csv")

  number_multiple_calls_single_patient <- epr_cohort[patient_record_order != 1, .N]
  
  number_individual_patients <- epr_cohort[patient_record_order == 1, .N]

  number_aged_under_sixteen <- epr_cohort[patient_record_order == 1][ssot_calculated_age < 16, .N]
  
  final_study_population <- epr_cohort[patient_record_order == 1 & ssot_calculated_age > 15, .N]
  
  
## Create table with numbers in
  
  strobe_numbers_table <- data.table(variable_name = c("number_ems_attendances_by_yas", "attendences_not_possible_to_trace",
                                                       "linkable_ems_attendences_by_yas","multiple_or_excluded_calls_records",
                                                       "individual_patients_excluded_removed", "under_sixteen",
                                                       "adult_cohort_count"),
                                     count = c(number_amb_attendences, number_attendences_not_linked,
                                               number_attendences_linked, (number_excluded_patients + number_multiple_calls_single_patient),
                                               number_individual_patients, number_aged_under_sixteen,
                                               final_study_population))


```

Table with figures need for Pre-Hospital PRIEST Triage/ePR STROBE diagram

```{r strobe_figurs_table, echo=FALSE}

kable(strobe_numbers_table)

```

